# Generated by Django 4.2.19 on 2025-02-28 19:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_attendance_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('qr_expiry', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted')], default='open', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='management.lecture'),
            preserve_default=False,
        ),
    ]
